// WARNING: Do not modify. This file is machine-generated by swagger-gen.

package models

import (
	"fmt"
)

// BaseB is machine-generated.
//
// The second polymorphic implementation of Base.
//
// BaseB conforms to:
// - Base
type BaseB struct {
	// The date-time that this object was created at.
	//
	// CreatedAt is nullable.
	CreatedAt *JSONDateTime `json:"created_at"`

	// The status.
	Status BaseBStatus `json:"status"`

	// The discriminator for the base model.
	Type BaseBType `json:"type"`
}

// BaseB's conformance to Base is machine-generated.

// GetCreatedAt is machine-generated.
//
// Gets BaseB's CreatedAt property.
func (o BaseB) GetCreatedAt() (*JSONDateTime, error) {
	return o.CreatedAt, nil
}

// GetType is machine-generated.
//
// Gets BaseB's Type property.
func (o BaseB) GetType() (string, error) {
	return string(o.Type), nil
}

type BaseBStatus int

const (
		SuccessEnumValue BaseBStatus = iota
		ErrorEnumValue
		CancelledEnumValue
)

func (e BaseBStatus) String() (string, error) {
	switch e {
		case SuccessEnumValue:
			return "success", nil
		case ErrorEnumValue:
			return "error", nil
		case CancelledEnumValue:
			return "cancelled", nil
		default:
			return "", fmt.Errorf("Bad BaseBStatus value %v.", e)
	}
}

func (e BaseBStatus) MarshalJSON() ([]byte, error) {
	str, err := e.String()
	if err != nil {
		return nil, err
	}
	return []byte(fmt.Sprintf("%+q", str)), nil
}

type BaseBType string

const BaseBTypeValue = "Base_B"

func (o BaseBType) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%+q", BaseBTypeValue)), nil
}
