// WARNING: Do not modify. This file is machine-generated by swagger-gen.

package models

import (
	"fmt"
)

// BaseA is machine-generated.
//
// The first polymorphic implementation of Base.
//
// BaseA conforms to:
// - Base
type BaseA struct {
	// The date-time that this object was created at.
	//
	// CreatedAt is nullable.
	CreatedAt *JSONDateTime `json:"created_at"`

	// The duration.
	Duration float64 `json:"duration"`

	// The discriminator for the base model.
	Type BaseAType `json:"type"`
}

// BaseA's conformance to Base is machine-generated.

// GetCreatedAt is machine-generated.
//
// Gets BaseA's CreatedAt property.
func (o BaseA) GetCreatedAt() (*JSONDateTime, error) {
	return o.CreatedAt, nil
}

// GetType is machine-generated.
//
// Gets BaseA's Type property.
func (o BaseA) GetType() (string, error) {
	return string(o.Type), nil
}

type BaseAType string

const BaseATypeValue = "Base_A"

func (o BaseAType) MarshalJSON() ([]byte, error) {
	return []byte(fmt.Sprintf("%+q", BaseATypeValue)), nil
}
