// WARNING: Do not modify. This file is machine-generated by swagger-gen.

package models

// PageOfBase is machine-generated.
//
// A page of Base objects.
type PageOfBase struct {
	Items []Base `json:"items"`
}
